name: flutter_epsilon_v2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  fpdart: ^1.1.1
  get_it: ^8.0.3
  go_router: ^15.0.0
  google_fonts: ^6.2.1
  hydrated_bloc: ^10.0.0
  mocktail: ^1.0.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
